image: gitpod/workspace-node-lts

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

tasks:
  - name: Build & Start App
    init: |
      npm install
      npm run build
    command: npm start
